### ISSUE TITLE
Keyboard flashing in Chrome

### ISSUE THREAD

**Issue by curiousdannii** [curiousdannii/infocom-frotz#13]
The virtual keyboard now no longer stays up.

**Comment by dfabulich** [comment]
Same in Safari.

**Comment by curiousdannii** [comment]
I think this is fixed now. I think the cause was that we have a locally modified version of `registerTouchEventCallback` (for high pixel density shenanigans). When I updated to Emscripten 3.1.62 our local version was no longer writing the event struct correctly, so that SDL could no longer make sense of the event. This then meant that `ev.preventDefault()` was called (or wasn't called, the reverse of whatever should have happened, I don't know which), and our code that tried to focus the keyboard stopped working properly.

I've now updated to Emscripten 3.1.65 and updated my modifications to `registerTouchEventCallback` so that it writes the struct correctly.
