### ISSUE TITLE
Journey: Clickable arrow keys

### ISSUE THREAD

**Issue by dfabulich** [curiousdannii/infocom-frotz#8]
You can operate Journey by clicking on the dialog items, but you can also operate it with arrow keys; that may not be obvious to players, and mobile keyboards don't have arrow keys.

Instead, it would be great to have on-screen "Left" "Right" "Up" "Down" buttons that send those keystrokes to the game.

This might be easier than implementing #1

**Comment by curiousdannii** [comment]
Pretty much the same as #7
